name: Main

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: curl ip-api.com
      - run: curl -fsSL https://github.com/masonr/yet-another-bench-script/raw/master/yabs.sh | bash
      - run: npm install -g bats
      - run: bats -v
